### ISSUE TITLE
transfer repo to be under phoenix-framework organization?

### ISSUE THREAD

**Issue by jeregrine** [phoenixframework/phoenix-guides#161]
To help people find them more quickly. @lancehalvorsen you can still be admin on the repo and etc :)

**Comment by lancehalvorsen** [comment]
We're getting to the point where this is probably the right call. :) Can there be multiple "owners" of the project? (seems like there can be) That would add flexibility in the long run.

@chrismccord, thoughts?

**Comment by kgish** [comment]
Not sure what the advantages would be, as long as people can find it via a link why bother?

**Comment by chrismccord** [comment]
> Can there be multiple "owners" of the project? (seems like there can be) That would add flexibility in the long run.

Only one org can own a project, but I have set up a `phoenix-docs` team that can share access to the project.

**Comment by stevedomin** [comment]
:+1: 

I've seen a couple of people asking where they could find the docs sources

**Comment by josevalim** [comment]
@lancehalvorsen can you give me admin access to this repo? Then I will do the migration today.

**Comment by josevalim** [comment]
Apparently we cannot add admins to personal repos. @lancehalvorsen can you transfer this repo to me?

**Comment by lancehalvorsen** [comment]
@josevalim, will do. I have to head off for the train right now, but this will happen today.

**Comment by lancehalvorsen** [comment]
@josevalim, this is becoming almost comical. :^)  I can't transfer ownership to you because github says that josevalim/phoenix-guides already exists. Perhaps if you delete your fork this will work?

Persistence will pay off!

**Comment by jeregrine** [comment]
We should send this thread to someone who works at Github :P

**Comment by josevalim** [comment]
Ok, I have deleted my repo. :P

**Comment by lancehalvorsen** [comment]
Ok, no errors, so maybe? :)

/cc @josevalim

**Comment by josevalim** [comment]
We did it!!!!!!! https://github.com/phoenixframework/phoenix-guides :heart_eyes_cat:

**Comment by lancehalvorsen** [comment]
:+1:

**Comment by jeregrine** [comment]
:tada: :confetti_ball: !!

**Comment by chrismccord** [comment]
Great work everybody! Computers!
